@baseURL = http://localhost:3000/api/usuario

### Orador User POST
POST {{baseURL}}/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "usuario": "orador1",
  "contrasenia": "orador1",
  "tipo_usuario": {
    "id_tipo_usuario": 3
  },
  "nombres": "Oscar Alfredo",
  "apellidos": "Menacho Silva",
  "fecha_nacimiento": "08/28/2002",
  "ciudad": {
    "id_ciudad": 3
  },
  "telefono": 75483958,
  "correo_electronico": "osqui@gmail.com"
}

### Personal User POST
POST {{baseURL}}/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "usuario": "personal1",
  "contrasenia": "personal1",
  "tipo_usuario": {
    "id_tipo_usuario": 2
  },
  "nombres": "Rodrigo Gabriel",
  "apellidos": "Rivera Mayan",
  "fecha_nacimiento": "04/20/2002",
  "ciudad": {
    "id_ciudad": 3
  },
  "telefono": 71289034,
  "correo_electronico": "rodri@gmail.com"
}

### Asistente User POST
POST {{baseURL}}/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "usuario": "asistente1",
  "contrasenia": "asistente1",
  "tipo_usuario": {
    "id_tipo_usuario": 4
  },
  "nombres": "José Andrés",
  "apellidos": "Manzaneda",
  "fecha_nacimiento": "03/15/2002",
  "ciudad": {
    "id_ciudad": 3
  },
  "telefono": 67859402,
  "correo_electronico": "jose@gmail.com"
}
